services:
  app:
    image: antoinezanardi/werewolves-assistant-api-dev
    container_name: app-dev
    depends_on:
      - mongodb
    environment:
      ENVIRONMENT: "development"
      HOST: "0.0.0.0"
      DATABASE_HOST: "mongodb-dev"
      DATABASE_PORT: "27017"
      DATABASE_NAME: "werewolves-assistant"
      DATABASE_USERNAME: "dev"
      DATABASE_PASSWORD: "speed_burger_is_the_best"
    build:
      context: ../../
      target: development
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  mongodb:
    container_name: mongodb-dev
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: "dev"
      MONGO_INITDB_ROOT_PASSWORD: "speed_burger_is_the_best"
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

volumes:
  mongodb_data_container: