const ROLE_NAMES = [
  "werewolf",
  "big-bad-wolf",
  "accursed-wolf-father",
  "white-werewolf",
  "villager",
  "villager-villager",
  "seer",
  "cupid",
  "witch",
  "hunter",
  "little-girl",
  "defender",
  "elder",
  "scapegoat",
  "idiot",
  "two-sisters",
  "three-brothers",
  "fox",
  "bear-tamer",
  "stuttering-judge",
  "rusty-sword-knight",
  "thief",
  "wild-child",
  "wolf-hound",
  "angel",
  "pied-piper",
  "scandalmonger",
  "prejudiced-manipulator",
  "actor",
  "devoted-servant",
] as const;

export { ROLE_NAMES };