services:
  app:
    image: antoinezanardi/werewolves-assistant-api-production
    container_name: app-production
    depends_on:
      - mongodb
    environment:
      ENVIRONMENT: "production"
      HOST: "0.0.0.0"
      PORT: "8082"
      DATABASE_HOST: "mongodb-production"
      DATABASE_PORT: "27017"
      DATABASE_NAME: "werewolves-assistant"
      DATABASE_USERNAME: "production"
      DATABASE_PASSWORD: "a_very_good_password"
    build:
      context: ../../
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  mongodb:
    container_name: mongodb-production
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: "production"
      MONGO_INITDB_ROOT_PASSWORD: "a_very_good_password"
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - "28000:27017"
    restart: unless-stopped

volumes:
  mongodb_data_container: