module.exports = {
  cleanTempDir: "always",
  incremental: true,
  incrementalFile: "tests/stryker/incremental.json",
  checkers: ["typescript"],
  tsconfigFile: "tsconfig.json",
  testRunner: "jest",
  ignoreStatic: true,
  mutate: [
    "src/**/*.ts",
    "!**/*.dto.ts",
    "!**/*.schema.ts",
    "!**/*.constant.ts",
  ],
  plugins: [
    "@stryker-mutator/jest-runner",
    "@stryker-mutator/typescript-checker",
  ],
  ignorePatterns: [
    "!.nuxt/",
    ".github/",
    ".husky/",
    ".output/",
    ".run/",
    ".idea/",
    "config/commitlint",
    "config/cucumber",
    "config/eslint",
    "config/lint-staged",
    "config/stryker",
    "tests/acceptance",
    "tests/stryker",
    "tests/unit/coverage",
    "scripts/",
    ".editorconfig",
    ".npmrc",
    ".nvmrc",
    ".releaserc.js",
    ".DS_Store",
    ".validate-branch-namerc.json",
    "CHANGELOG.md",
    "LICENSE",
    "pnpm-lock.yaml",
    "sonar-project.properties",
    "README.md",
  ],
  jest: { configFile: "config/jest/jest-global.ts" },
  reporters: ["clear-text", "progress", "html", "json"],
  htmlReporter: { fileName: "tests/stryker/coverage/index.html" },
  jsonReporter: { fileName: "tests/stryker/coverage/mutation.json" },
  thresholds: {
    high: 100,
    low: 100,
    break: 100,
  },
  disableTypeChecks: "{tests,src,lib}/**/*.{js,ts,jsx,tsx,html,vue}",
};