enum BadGamePlayPayloadReasons {
  UNEXPECTED_STUTTERING_JUDGE_VOTE_REQUEST = "`doesJudgeRequestAnotherVote` can't be set on this current game's state",
  UNEXPECTED_CHOSEN_SIDE = "`chosenSide` can't be set on this current game's state",
  REQUIRED_CHOSEN_SIDE = "`chosenSide` is required on this current game's state",
  UNEXPECTED_CHOSEN_CARD = "`chosenCard` can't be set on this current game's state",
  THIEF_MUST_CHOOSE_CARD = "Thief must choose a card (`chosenCard`)",
  CHOSEN_CARD_NOT_FOR_THIEF = "Chosen card is not for thief",
  CHOSEN_CARD_NOT_FOR_ACTOR = "Chosen card is not for actor",
  CHOSEN_CARD_ALREADY_USED = "Chosen card is already used",
  UNEXPECTED_VOTES = "`votes` can't be set on this current game's state",
  REQUIRED_VOTES = "`votes` is required on this current game's state",
  SAME_SOURCE_AND_TARGET_VOTE = "One vote has the same source and target",
  BAD_VOTE_SOURCE = "One source is not able to vote because he's dead or doesn't have the ability to do so",
  BAD_VOTE_TARGET = "One target can't be voted because he's dead",
  BAD_VOTE_TARGET_FOR_TIE_BREAKER = "One vote's target is not in the previous tie in votes",
  UNEXPECTED_TARGETS = "`targets` can't be set on this current game's state",
  REQUIRED_TARGETS = "`targets` is required on this current game's state",
  TOO_LESS_TARGETS = "There are too less targets for this current game's state",
  TOO_MUCH_TARGETS = "There are too much targets for this current game's state",
  UNEXPECTED_DRANK_POTION_TARGET = "`targets.drankPotion` can't be set on this current game's state",
  TOO_MUCH_DRANK_LIFE_POTION_TARGETS = "There are too much targets which drank life potion (`targets.drankPotion`)",
  BAD_LIFE_POTION_TARGET = "Life potion can't be applied to this target (`targets.drankPotion`)",
  TOO_MUCH_DRANK_DEATH_POTION_TARGETS = "There are too much targets which drank death potion (`targets.drankPotion`)",
  BAD_DEATH_POTION_TARGET = "Death potion can't be applied to this target (`targets.drankPotion`)",
  BAD_WEREWOLVES_TARGET = "Werewolves can't eat this target",
  BAD_WHITE_WEREWOLF_TARGET = "White werewolf can't eat this target",
  BAD_BIG_BAD_WOLF_TARGET = "Big bad wolf can't eat this target",
  BAD_ACCURSED_WOLF_FATHER_TARGET = "Accursed Wolf-father can't infect this target",
  BAD_HUNTER_TARGET = "Hunter can't shoot this target",
  BAD_SCAPEGOAT_TARGETS = "At least one of the scapegoat targets can't be banned from voting",
  BAD_CUPID_TARGETS = "At least one of the cupid targets can't be charmed",
  BAD_FOX_TARGET = "Fox can't sniff this target",
  BAD_SEER_TARGET = "Seer can't look at this target",
  BAD_SCANDALMONGER_TARGET = "Scandalmonger can't mark this target",
  BAD_WILD_CHILD_TARGET = "Wild child can't choose this target as a model",
  BAD_PIED_PIPER_TARGETS = "At least one of the pied piper targets can't be charmed",
  BAD_DEFENDER_TARGET = "Defender can't protect this target",
  BAD_SHERIFF_DELEGATE_TARGET = "Sheriff can't delegate his role to this target",
  BAD_SHERIFF_SETTLE_VOTES_TARGET = "Sheriff can't break the tie in votes with this target",
  DEVOTED_SERVANT_CANT_STEAL_ROLE = "Devoted servant can't steal the role of this target because she's not in the game or dead or powerless or in love with another player",
  BAD_DEVOTED_SERVANT_TARGET = "Devoted servant can't steal the role of this target because he's not about to be buried",
}

export { BadGamePlayPayloadReasons };