enum BAD_GAME_PLAY_PAYLOAD_REASONS {
  UNEXPECTED_STUTTERING_JUDGE_VOTE_REQUEST = "`doesJudgeRequestAnotherVote` can't be set on this current game's state",
  UNEXPECTED_CHOSEN_SIDE = "`chosenSide` can't be set on this current game's state",
  REQUIRED_CHOSEN_SIDE = "`chosenSide` is required on this current game's state",
  UNEXPECTED_CHOSEN_CARD = "`chosenCard` can't be set on this current game's state",
  REQUIRED_CHOSEN_CARD = "`chosenCard` is required on this current game's state",
  UNEXPECTED_VOTES = "`votes` can't be set on this current game's state",
  REQUIRED_VOTES = "`votes` is required on this current game's state",
  SAME_SOURCE_AND_TARGET_VOTE = "One vote has the same source and target",
  BAD_VOTE_TARGET_FOR_TIE_BREAKER = "One vote's target is not in the previous tie in votes",
  UNEXPECTED_TARGETS = "`targets` can't be set on this current game's state",
  REQUIRED_TARGETS = "`targets` is required on this current game's state",
  TOO_LESS_TARGETS = "There are too less targets for this current game's state",
  TOO_MUCH_TARGETS = "There are too much targets for this current game's state",
  UNEXPECTED_DRANK_POTION_TARGET = "`targets.drankPotion` can't be set on this current game's state",
  TOO_MUCH_DRANK_LIFE_POTION_TARGETS = "There are too much targets which drank life potion (`targets.drankPotion`)",
  BAD_LIFE_POTION_TARGET = "Life potion can't be applied to this target (`targets.drankPotion`)",
  TOO_MUCH_DRANK_DEATH_POTION_TARGETS = "There are too much targets which drank death potion (`targets.drankPotion`)",
  BAD_DEATH_POTION_TARGET = "Death potion can't be applied to this target (`targets.drankPotion`)",
  UNEXPECTED_INFECTED_TARGET = "`targets.isInfected` can't be set on this current game's state",
  BAD_WEREWOLVES_TARGET = "Werewolves can't eat this target",
  BAD_WHITE_WEREWOLF_TARGET = "White werewolf can't eat this target",
  BAD_BIG_BAD_WOLF_TARGET = "Big bad wolf can't eat this target",
  BAD_HUNTER_TARGET = "Hunter can't shoot this target",
  BAD_SCAPEGOAT_TARGETS = "At least one of the scapegoat targets can't be banned from voting",
  BAD_CUPID_TARGETS = "At least one of the cupid targets can't be charmed",
  BAD_FOX_TARGET = "Fox can't sniff this target",
  BAD_SEER_TARGET = "Seer can't look at this target",
  BAD_RAVEN_TARGET = "Raven can't mark this target",
  BAD_WILD_CHILD_TARGET = "Wild child can't choose this target as a model",
  BAD_PIED_PIPER_TARGETS = "At least one of the pied piper targets can't be charmed",
  BAD_GUARD_TARGET = "Guard can't protect this target",
  BAD_SHERIFF_DELEGATE_TARGET = "Sheriff can't delegate his role to this target",
  BAD_SHERIFF_SETTLE_VOTES_TARGET = "Sheriff can't break the tie in votes with this target",
}

export { BAD_GAME_PLAY_PAYLOAD_REASONS };