version: "3.8"
services:
  mongo:
    container_name: "mongo-dev"
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: speed_burger_is_the_best
    ports:
      - "27019:27017"
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: